#! /bin/bash
# "MetaGit" - a command for using git on the .git folder of the current git repo
mgit() {
        (
                gitroot="$(git rev-parse --show-toplevel)"
                [ $? == 0 ] || {
                        echo "MetaGit can only be run inside a Git repo, exiting."
                        exit
                }
                cd "$gitroot/.git"
                git "$@"
        )
}

explore() {
        if [ -z "$1" ]; then
                /bin/cygstart --explore `pwd`
        else
                /bin/cygstart --explore $@
        fi
}

function nonono() {
        while true; do
                printf "no "
                sleep 1
        done
}

function DoctorNo() {
        while true; do
                echo "Ask me anything?"
                read;
                echo "No."
        done
}

function termcolors() {
	for clbg in {40..47} {100..107} 49 ; do
		#Foreground
		for clfg in {30..37} {90..97} 39 ; do
			#Formatting
			for attr in 0 1 2 4 5 7 ; do
				#Print the result
				echo -en "\e[${attr};${clbg};${clfg}m ^[${attr};${clbg};${clfg}m \e[0m"
			done
			echo #Newline
		done
	done
}

# lazy open
function a() {
        if [ -d "$*" ]; then
                cd "$*"
                return
        fi
        vim "$*"
}

# echo then run command
function erun() {
       echo "\"$@\""
       $@
}
